# -*- coding: utf-8 -*-
"""Kelembapan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tqX2Irhhksp-TwAbAgqfSwsF_OPNvYcg
"""

# ============================================================
# Instal pustaka scikit-fuzzy
# ============================================================
!pip -q install scikit-fuzzy

import numpy as np
import skfuzzy as fuzz
import matplotlib.pyplot as plt

# ============================================================
# Domain variabel input kelembapan
# Satuan: persen (%)
# Sesuai domain pada sistem fuzzy
# ============================================================
kelembapan = np.arange(0, 100.1, 0.1)

# ============================================================
# Fungsi keanggotaan variabel input kelembapan
# Sesuai dengan CODE_FUZZY_LOGIC_SKRIPSI.ino
# ============================================================

# Sangat Kering: trapmf(hum, 0.0, 0.0, 20.2, 25.0)
hum_sangat_kering = fuzz.trapmf(kelembapan, [0.0, 0.0, 20.2, 25.0])

# Kering: trimf(hum, 20.2, 30.0, 40.0)
hum_kering = fuzz.trimf(kelembapan, [20.2, 30.0, 40.0])

# Sedang: trimf(hum, 35.0, 50.0, 60.0)
hum_sedang = fuzz.trimf(kelembapan, [35.0, 50.0, 60.0])

# Lembap: trimf(hum, 55.0, 65.0, 73.5)
hum_lembap = fuzz.trimf(kelembapan, [55.0, 65.0, 73.5])

# Sangat Lembap: trapmf(hum, 70.0, 73.5, 100.0, 100.0)
hum_sangat_lembap = fuzz.trapmf(kelembapan, [70.0, 73.5, 100.0, 100.0])

# ============================================================
# Visualisasi fungsi keanggotaan variabel input kelembapan
# ============================================================
plt.figure(figsize=(10, 6))

plt.plot(kelembapan, hum_sangat_kering, linewidth=2.5, label='Sangat Kering')
plt.plot(kelembapan, hum_kering, linewidth=2.5, label='Kering')
plt.plot(kelembapan, hum_sedang, linewidth=2.5, label='Sedang')
plt.plot(kelembapan, hum_lembap, linewidth=2.5, label='Lembap')
plt.plot(kelembapan, hum_sangat_lembap, linewidth=2.5, label='Sangat Lembap')

plt.title('Fungsi Keanggotaan Variabel Input Kelembapan', fontsize=14)
plt.xlabel('Kelembapan (%)', fontsize=12)
plt.ylabel('Derajat Keanggotaan', fontsize=12)
plt.xlim(0, 100)
plt.ylim(0, 1.05)
plt.xticks(np.arange(0, 101, 10))
plt.yticks(np.arange(0, 1.1, 0.1))
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(loc='best', fontsize=10)
plt.tight_layout()

# ============================================================
# Simpan gambar untuk kebutuhan skripsi
# ============================================================
plt.savefig('fungsi_keanggotaan_kelembapan.png', dpi=300, bbox_inches='tight')

plt.show()